services:
  # Socket.IO Service
  - type: web
    name: poll-app-socket
    env: node
    nodeVersion: 22
    plan: starter
    buildCommand: npm install && npm run build
    startCommand: npm run start:socket
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        sync: false
      - key: FRONTEND_URL
        sync: false
      - key: SOCKET_PORT
        value: 10000
    healthCheckPath: /health

